on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
jobs:
  main:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ inputs.username }}"
