on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      repo:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
jobs:
  main:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ inputs.username }} in ${{ inputs.repo }}"
