on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
jobs:
  main:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build
